### ISSUE TITLE
brew install should work if I don't already have carthage installed.

### ISSUE THREAD

**Issue by younata** [tjarratt/Xcode-Better-Refactor-Tools#16]
The brew recipe doesn't mention carthage, even though it's used for building it.

This means that when I try to install this tool on a brand new machine, I run into the error, facepalm, install carthage, then re-try installing fake4swift.

Please, fix this. My face is thinking of getting a restraining order against my palm to stop the violence.

**Comment by tjarratt** [comment]
Fixed as of v3.0.5 in fake4swift, along with a bunch of ugly hacks in our Makefile.

Checkout the history on this one, it's a goddamn doozy. In short, homebrew really, really doesn't like it if your formula depends on other formula, so we have to go to some gross lengths in order to bring down carthage as part of building the CLI.
