### ISSUE TITLE
Fake Protocol Generation should generate objects that conform to Equatable

### ISSUE THREAD

**Issue by younata** [tjarratt/Xcode-Better-Refactor-Tools#7]
Essentially, needs to conform to equatable in the class declaration, then adds a top-level function implementing "=="

Something like: 

``` swift
// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

class FakeMyProtocol : MyProtocol, Equatable {
    private let hash: Int = Int(arc4random())

    init() {
    }

    static func reset() {
    }
}

func ==(a: FakeMyProtocol, b: FakeMyProtocol) -> Bool {
    return a.hash == b.hash
}
```

The hash w/ arc4random call is not optimal, but was just the first thing that came to mind.

**Comment by tjarratt** [comment]
Closed through 6a02b11db49c8c34983ebf47a82d9d5ce555ec87 and 98a2d9a27242c9edee9762493d4c45052f43b827.

Thanks for the suggestion @younata. I actually used your implementation above for fakes that need to be implemented by structs, because of some interesting rules in swift around comparing arrays of equatable types.

For fun, you might want to read [Chris Lattner's post on the dev forums about comparing closures for pointer equality](https://devforums.apple.com/message/1035180#1035180). It's ... yeah. Wow.
